server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto_job_plus?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    password: "0000"
    username: root
mybatis-plus:
  # 扫描指定包名下的entity接口，在写相应的映射xml文件时可以不指定全类名
  type-aliases-package: com.example.**.pojo
  # 扫描指定路径下的mapper映射文件
  mapper-locations:
    - classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名映射
    map-underscore-to-camel-case: true